name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GCP_PROJECT_ID length
        run: echo "GCP_PROJECT_ID length is ${#GCP_PROJECT_ID}"
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Print GCP_SA_KEY length
        run: echo "GCP_SA_KEY length is ${#GCP_SA_KEY}"
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Print gcloud auth list
        run: gcloud auth list

      - name: Print gcloud config list
        run: gcloud config list

      - name: Build and push Docker image
        run: |
          echo "Building Docker image for project ${{ secrets.GCP_PROJECT_ID }}"
          BUILD_ID=$(gcloud builds submit backend --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/library-system-api --async --format="value(id)")
          echo "Build ID: $BUILD_ID"
          
          # Wait for build to complete
          echo "Waiting for build to complete..."
          while true; do
            STATUS=$(gcloud builds describe $BUILD_ID --format="value(status)")
            echo "Build status: $STATUS"
            if [ "$STATUS" = "SUCCESS" ]; then
              echo "Build completed successfully!"
              break
            elif [ "$STATUS" = "FAILURE" ] || [ "$STATUS" = "TIMEOUT" ] || [ "$STATUS" = "CANCELLED" ]; then
              echo "Build failed with status: $STATUS"
              exit 1
            fi
            sleep 10
          done

      - name: Print gcloud run services list
        run: gcloud run services list --region us-west1

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run in project ${{ secrets.GCP_PROJECT_ID }}"
          gcloud run deploy library-system-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/library-system-api \
            --region us-west1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
            --add-cloudsql-instances marine-potion-470417-c7:us-west1:library-system \
            --set-env-vars DATABASE_URL="${{ secrets.DATABASE_URL }}"

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend  # Wait for backend to deploy first
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get backend URL
        id: backend-url
        run: |
          BACKEND_URL=$(gcloud run services describe library-system-api --region us-west1 --format="value(status.url)")
          echo "backend_url=$BACKEND_URL" >> $GITHUB_OUTPUT
          echo "Backend URL: $BACKEND_URL"

      - name: Build and push Frontend Docker image
        run: |
          echo "Building Frontend Docker image for project ${{ secrets.GCP_PROJECT_ID }}"
          BUILD_ID=$(gcloud builds submit frontend --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/library-system-frontend --async --format="value(id)" --config frontend/cloudbuild.yaml)
          echo "Frontend Build ID: $BUILD_ID"
          
          # Wait for build to complete
          echo "Waiting for frontend build to complete..."
          while true; do
            STATUS=$(gcloud builds describe $BUILD_ID --format="value(status)")
            echo "Frontend build status: $STATUS"
            if [ "$STATUS" = "SUCCESS" ]; then
              echo "Frontend build completed successfully!"
              break
            elif [ "$STATUS" = "FAILURE" ] || [ "$STATUS" = "TIMEOUT" ] || [ "$STATUS" = "CANCELLED" ]; then
              echo "Frontend build failed with status: $STATUS"
              exit 1
            fi
            sleep 10
          done

      - name: Deploy Frontend to Cloud Run
        run: |
          echo "Deploying Frontend to Cloud Run in project ${{ secrets.GCP_PROJECT_ID }}"
          gcloud run deploy library-system-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/library-system-frontend \
            --region us-west1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars NEXT_PUBLIC_API_URL="${{ steps.backend-url.outputs.backend_url }}" \
            --memory=512Mi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=10 \
            --concurrency=80 \
            --timeout=300

      - name: Get Frontend URL
        run: |
          FRONTEND_URL=$(gcloud run services describe library-system-frontend --region us-west1 --format="value(status.url)")
          echo "🎉 Frontend deployed successfully!"
          echo "📱 Frontend URL: $FRONTEND_URL"
          echo "🔗 Backend URL: ${{ steps.backend-url.outputs.backend_url }}"
