name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GCP_PROJECT_ID
        run: echo "GCP_PROJECT_ID is ${{ secrets.GCP_PROJECT_ID }}"

      - name: Print GCP_SA_KEY length
        run: echo "GCP_SA_KEY length is $(echo '${{ secrets.GCP_SA_KEY }}' | wc -c)"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Print gcloud auth list
        run: gcloud auth list

      - name: Print gcloud config list
        run: gcloud config list

      - name: Build and push Docker image
        run: |
          echo "Building Docker image for project ${{ secrets.GCP_PROJECT_ID }}"
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/library-system-api

      - name: Print gcloud run services list
        run: gcloud run services list --region us-central1

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run in project ${{ secrets.GCP_PROJECT_ID }}"
          gcloud run deploy library-system-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/library-system-api \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
