name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/library-system-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy library-system-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/library-system-api \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
